### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by code-tieumomo** [IMTALabs/lms#6]
**Is your feature request related to a problem? Please describe.**
- Chỉnh sửa một số phần nhỏ trên giao diện

**Describe the solution you'd like**
- Thay đổi thiết kế header (cẩn thận tránh thiếu mất chức năng), footer: Phần này có thể tham khảo một số template trên [Themeforest](https://themeforest.net/), tùy ý quyết định
- Thay đổi màu sắc chủ đạo cho trang web: Phần này chú ý xem các biến trong CSS, nên đổi giá trị của biến để tránh phải sửa tay nhiều chỗ
- Thay đổi một số ảnh và icon trên trang nếu cần thiết: Icon tham khảo [Icones](https://icones.js.org/), sử dụng `<svg>` luôn không cần lưu file về, còn ảnh thì nên tải về và để trong thư mục ảnh ở `public`

**Describe alternatives you've considered**
- N/A

**Additional context**
- N/A

**Comment by HoangCOngTIenRider** [comment]
footer : sửa màu , bỏ link k cần thiết 
header:

- [ ] bỏ box-shadow thay bằng border
- [ ] xóa ô search 
- [ ] bỏ nút become
- [ ] nhỏ avatar
- [ ] bỏ background ở category
- [ ] chình lại pading của menu category
- [ ] hover cả icon
- [ ] giảm boder-radius của menu 
- [ ] bỏ icon giỏ hàng
